on:
    push:
        branches:
            - "master"
    schedule:
        - cron: '0 * * * *'

jobs:
    docker:
        runs-on: ubuntu-22.04
        steps:
            - 
                name: Checkout
                uses: actions/checkout@v3
            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            - 
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            - 
                name: Build and push artifact
                uses: docker/build-push-action@v3
                with:
                    context: .
                    file: Dockerfile.rootfs
                    push: true
                    tags: simpletoimplement/artifacts:alpine-rootfs
                    platforms: linux/amd64
            -
                name: Extract rootfs
                uses: shrink/actions-docker-extract@v2
                id: extract
                with:
                    image: simpletoimplement/artifacts:alpine-rootfs
                    path: /rootfs.tar.gz
            -
                name: Upload artifact
                uses: actions/upload-artifact@v2
                with:
                    path: ${{ steps.extract.outputs.destination }}
                    name: rootfs
            -
                name: Download artifact
                uses: actions/download-artifact@v3
                with:
                    name: rootfs
            -
                name: Build and push
                uses: docker/build-push-action@v3
                with:
                    context: .
                    push: true
                    tags: simpletoimplement/alpine:edge
                    platforms: linux/amd64,linux/arm64
